# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Alertmanager installation tasks
  block:
    - name: Validate Alertmanager configuration
      when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Prepare HTTP Basic Auth for Alertmanager
      when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"

    - name: Install Alertmanager
      when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-alertmanager
    - install-all
    - install-alertmanager

- name: Perform Alertmanager uninstallation tasks
  block:
    - name: Uninstall Alertmanager
      when: not alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-alertmanager
