# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- tags:
    - setup-all
    - setup-alertmanager
    - install-all
    - install-alertmanager
  block:
    - when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"

    - when: alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-alertmanager
  block:
    - when: not alertmanager_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
